/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TESTBDD.java
 *
 * Created on 21 oct. 2010, 17:06:49
 */
package testbdddarties;

import java.io.BufferedReader;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import oracle.jdbc.pool.OracleDataSource;

/**
 *
 * @author EMRIC
 */
public class TESTBDD extends javax.swing.JFrame {

    public String nomServeur = "localhost"; //ou pedagowin710.univ-lyon1.fr
    public int portServeur = 1521;
    public String nomBase = "orapeda1";
    public String login = "EPU3AGRP20";
    public String mdp = "EPU3AGRP20";
    public String requete = "select * from \"Continent\" ";
    Connection connect = null;

    public TESTBDD() {
        initComponents();

        jButton2.setEnabled(false);
        // 1- Fichier log
        try {
            System.out.println("Ouverture du fichier");
            BufferedReader fichier = new BufferedReader(new FileReader("./log.txt"));

            nomServeur = fichier.readLine();    // localhost ou pedagowin710.univ-lyon1.fr
            portServeur = Integer.parseInt(fichier.readLine());   //1521
            nomBase = fichier.readLine();       //orapeda1
            login = fichier.readLine();         //EPU3AGRP20
            mdp = fichier.readLine();           //EPU3AGRP20


            fichier.close();

        } catch (Exception e) {
            System.out.println("Erreur de lecture du fichier log");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Test BDD");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                fermeture(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SGBD", "ALIMENTATION", "RESTITUTION", "ETL" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Connection");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Lancer requete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                        .addContainerGap(18, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        String bdd = jComboBox1.getSelectedItem().toString();

        if (bdd.equals("SGBD")) {
            login = "EPU3AGRP20";
            mdp = "EPU3AGRP20";
        }
        if (bdd.equals("ALIMENTATION")) {
            login = "EPU3AGRP21";
            mdp = "EPU3AGRP21";
        }
        if (bdd.equals("RESTITUTION")) {
            login = "EPU3AGRP22";
            mdp = "EPU3AGRP22";
        }
        if (bdd.equals("ETL")) {
            login = "EPU3AGRP23";
            mdp = "EPU3AGRP23";
        }
        

        // 4- Ouverture de la connexion
        jTextArea1.setText("Tentative de connexion...");

        OracleDataSource ods = null;
        try {
            ods = new OracleDataSource();
        } catch (SQLException ex) {
            jTextArea1.setText("Problème ODBC");
        }

        // type de pilote oracle
        ods.setDriverType("thin");

        // nom de la machine sur laquelle se trouve la base
        ods.setServerName(nomServeur);
        //ods.setServerName("pedagowin710.univ-lyon1.fr");

        // numero du port pour se connecter à la base
        ods.setPortNumber(portServeur);

        // nom de la base
        ods.setDatabaseName(nomBase);

        // Ouverture de la connexion

        try {
            connect = ods.getConnection(login, mdp);
            jTextArea1.setText("...Connexion etablie avec succès.");
            jButton2.setEnabled(true);
            jButton1.setEnabled(false);
        } catch (SQLException ex) {
            jTextArea1.setText("Echec de la tentative de connexion");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // 5- Test sur la base
        Statement stat = null;
        try {
            stat = connect.createStatement();
        } catch (SQLException ex) {
            jTextArea1.setText("Echec creation requete");
        }

        try {
            ResultSet resultat = stat.executeQuery(requete);

            if (resultat.next()) {
                jTextArea1.setText("OK \nRequete : " +requete + "\nResulat : \nidContient "+resultat.getString("idContinent")+ "\nnomContinent "+ resultat.getString("nomContinent"));
            }

        } catch (SQLException ex) {
            jTextArea1.setText("Echec de la requete");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fermeture(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_fermeture
        // 6- Fermeture de la connexion
        try {
            connect.close();
        } catch (SQLException ex) {
            System.out.println("Echec de la fermeture de la connexion");
        }

        System.out.println("Fin du programme");
    }//GEN-LAST:event_fermeture

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TESTBDD().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
